### ISSUE TITLE
Rebrand: Suquo Systems logo + wordmark at every in-app DeepSeek logo site

### ISSUE THREAD

**Issue by chidi21** [Suquo/deepseek-harness-desktop#26]
OWNER REQUEST (2026-08-20, in-session): replace the DeepSeek logos in the app UI with the Suquo Systems logo, with the text 'Suquo Systems' next to the logo. Asset source (read-only grab, copy into this repo): C:/Users/chidi/Documents/suquo-systems-rust/apps/web/public/suquo-systems-logo-light.svg (note the -light suffix — check both themes; a dark variant may need deriving, flag if so). License basis verified: both layers MIT (rebranding permitted, notices retained — see RM license read, 2026-08-20 chat). SCOPE: in-app visual branding surfaces (Lane D: client-plugin CSS/layout/visual/theming). Ground FIRST where each DeepSeek logo renders (upstream client packages vs overlay code) — if any site is unreachable without upstream patches, Host changes, or packaging edits (installer icons, window icons, app name), the lane FREEZES with the exact surface list so the RM can re-scope those to the right lane. Both themes validated in the running app per Lane D charter. RM triage: APPROVED (owner-requested).

**Comment by chidi21** [comment]
Lane D resolver gen-1 CLAIMED #26. Branch: `dg/issue-26-suquo-rebrand` (from origin/master 2dec1307). Worktree `C:\Users\chidi\.dsh-resolver-worktrees\issue-26`, ports 3700+. Phase: grounding — enumerating every in-app DeepSeek logo site and where each is authored (overlay vs upstream packages vs Host/packaging).

**Comment by chidi21** [comment]
GROUND settled (upstream pin dsh-v0.1.0-rc.7). Three in-app mark renders, all upstream-authored, all CSS-reachable from the overlay's own `ADVANCED_STYLES` sheet: sidebar wordmark (`.hHd-Xa_brand`/`.hHd-Xa_logoRow`), sidebar rail fish (`.hHd-Xa_railFish`), empty-state hero fish (`.pXSMma_fish`/`.pXSMma_fishHitbox`) — geometry from `dsh-client-ui-primitives` `FishLogo`/`BrandWordmark`. Out-of-fence remainder confirmed (favicon/`<title>`/manifest need the Host `indexTaps` seam; tray+app icons, window title, productName, installer art are packaging; onboarding/provider copy is locale/server data) — so this PR will NOT close #26; exact surface list ships in the PR body as the freeze-report. Also: `$DSH_HOME` alone could not launch (Electron single-instance lock is keyed on the SHARED `%APPDATA%\DSH Desktop`); launching with `--user-data-dir` under the lane home gave a genuinely isolated instance — recipe disclosed in the PR body. Next: implement.

**Comment by chidi21** [comment]
Increment pushed: 62cfef6 — Suquo mark + 'Suquo Systems' wordmark wired into the advanced-shell stylesheet (`src/client/brand.ts` + `styles.ts`), source asset committed at `assets/suquo-systems-logo-light.svg`, fence `tests/client-brand.spec.ts` green (7/7). Mark is a CSS mask over `currentColor`, so one monochrome asset serves both themes — no dark variant needed. Next: graphical validation (both themes, both modes) from the lane-isolated instance.

**Comment by chidi21** [comment]
OWNER RIDER (2026-08-20, in-session): the UI text "Into the Unkown" (as rendered; likely spelled 'Into the Unknown' in source — search both spellings) changes to "Parametric Definitions". Same lane, same slice — ground where the string is authored (overlay vs upstream client package) under the same in-fence/freeze rules as the logo sites.

**Comment by chidi21** [comment]
Owner rider folded in — increment pushed: e567012. Grounding on the headline: upstream spells it `'Into the Unknown'` (one entry, `deepseek-harness/packages/client/ui-conversation/src/client/locales.ts:242`, key `hero.headline`; the misspelling 'Unkown' does not occur in the pinned bundle). The official locale path is CLOSED to us — `LocaleRuntime.register` is single-occupant and throws on a duplicate (namespace, locale), so the conversation package's namespace cannot be re-registered by a desktop client plugin. The replacement therefore rides the same overlay stylesheet as the marks: upstream's span is `display: none` (leaves the accessibility tree, not merely hidden) and the headline grid gets explicit `order`. Verified live in the running advanced shell. Fence extended (9/9): a pin that renames or retranslates `hero.headline` fails a named test. Next: both-theme GUI pass, then full gate.

**Comment by chidi21** [comment]
GUI pass done, full gate started. Both themes validated in the running lane instance (advanced mode): light — mark+wordmark render near-black (`rgb(15,17,21)`) on the white sidebar, hero reads 'Parametric Definitions'; dark — same sites render near-white (`rgb(249,250,251)`); collapsed rail shows the mark alone. Compatibility mode re-checked on the SAME build: no advanced-shell stylesheet, upstream wordmark (viewBox `0 0 182 24`) and whale intact, headline still 'Into the Unknown' — upstream default client runs unoverridden. Four fence mutations each produced a named failure and were reverted on a clean tree. Now running `corepack yarn check` foreground; PR next.

**Comment by chidi21** [comment]
OWNER DIRECTION CHANGE (2026-08-20, in-session — supersedes the original brief and the Suquo Systems logo/wordmark): branding is now **Parametria**, taken from the operator's Parametria app (00_SuquoStudio/.../parametria). Grounded treatment from that app's source: text wordmark `PARAMETRIA`, bold (fw 700), letter-spacing 0.05em, accent color `--ptx-accent` = #4fc3f7 (dark) / #0288d1 (light variant) — Toolbar.tsx:17-24 + Toolbar.module.css:12-16 + globals.css:63/287. There is NO image logo in that app; for logo sites that require a GRAPHIC (favicon-class), the mark at suquo-systems-rust/apps/web/components/icons/parametria-logo-icon.tsx is the available icon (read-only grab — no-modify ruling stands on that repo). The 'Into the Unkown' → 'Parametric Definitions' rider stands. Drop the suquo-systems-logo-light.svg direction entirely.

**Comment by chidi21** [comment]
Owner direction change absorbed — increment pushed: a7df81c. Suquo Systems asset + wordmark dropped from the branch. New treatment: sidebar lockup renders `PARAMETRIA` (700, 0.05em) in #0288d1 light / #4fc3f7 dark, keyed off the dark-theme attribute the desktop theme presenter already sets; the two graphic-only sites (56px collapsed rail, inline hero mark) take the Parametria icon vendored verbatim from `parametria-logo-icon.tsx` with its documented brand blues intact — read-only grab, that repo untouched. Verified live in both themes: measured `rgb(2,136,209)` light and `rgb(79,195,247)` dark, weight 700, tracking 0.75px (=0.05em). Compatibility mode re-checked on the same build: no advanced sheet, upstream wordmark + whale intact, headline still 'Into the Unknown'. Also folded in this branch's self-review (inert `order` replaced by the grid cell upstream assigns; drift guards re-anchored on each bundle's CSS-module export mapping; headline guard now key-anchored across both locales; ADR H-0002 added). Next: mutation proofs + full gate, then PR.

**Comment by chidi21** [comment]
PR opened: #28 (head 55e2c0e). Gate `corepack yarn check` exit 0 on the committed tree (60 files / 593 passed / 11 skipped); five fence mutations each produced a named failure and were reverted. `closingIssuesReferences` verified EMPTY — #28 does not close this issue, by design: the freeze-report remainder ships in its body (web-shell title/favicon/manifest via the Host `indexTaps` seam; tray + app icons, `windowTitle`, `productName`, installer art; locale/server-authored DeepSeek copy). RULING NEEDED, stated at the top of the PR: compatibility mode is the DEFAULT shell mode and the only mode on Linux, and AGENTS.md requires it to run the upstream default client without overrides — so on a default install the Parametria branding is not visible until the user switches to advanced mode. I did not override it; moving that rule is an owner call. Lane D generation 1 ending here.

**Comment by chidi21** [comment]
IN-APP BRANDING MERGED (PR #28): PARAMETRIA wordmark + mark live in desktop-composed modes, 'Parametric Definitions' headline, both themes, ADR H-0002. THIS ISSUE STAYS OPEN on the re-scoped REMAINDER (out of Lane D's fence, from the PR's freeze report): (1) web-shell <title>/favicon/manifest via the Host indexTaps seam; (2) tray + app icons, windowTitle, productName, installer art (packaging-gated: verify:closure + check:win-package apply); (3) locale/server-authored DeepSeek copy; (4) rider from review: one-line aria-label drift guard in client-brand.spec.ts's it.each (the corrected lockup comment rests on a pinned upstream aria-label with no guard behind it). PENDING OWNER: whether compatibility mode (default shell) may carry branding — AGENTS.md currently forbids overrides there; universal branding needs that doctrine ruling first. Lane assignment for the remainder: Lane A or B (Host/packaging — NOT Lane D). RM triage: APPROVED, claimable after the owner's compat ruling or independently for items 1/2/4.

**Comment by chidi21** [comment]
OWNER RULING (2026-08-20, in-session): **BRAND EVERYWHERE** — the operator launched the default (compatibility) shell and expects PARAMETRIA branding there. AGENTS.md amended accordingly (visual branding overrides permitted in compat mode, presentation-only, behavior stays unoverridden). This unblocks the full remainder: compat-mode brand styles + web-shell title/favicon/manifest (indexTaps) + tray/app icons/windowTitle/productName/installer art (packaging-gated) + locale copy + the aria-label guard one-liner. Lane A slice, spawning now.

**Comment by chidi21** [comment]
Lane A resolver gen-4 CLAIMED the #26 REMAINDER. Branch: `claude/issue-26-host-branding` (from origin/master aa7014f7), worktree `C:\Users\chidi\.dsh-resolver-worktrees\issue-26h`, ports 3400+. Scope = the Host/packaging half unblocked by the BRAND-EVERYWHERE ruling: (1) compat-mode brand visibility, (2) web-shell `<title>`/favicon/manifest via the Host index seam, (3) windowTitle/tray/app icons/productName (packaging-gated), (4) the aria-label drift-guard rider in `tests/client-brand.spec.ts`, (5) locale/server-authored copy enumerated + deferred-with-reasons. Disjoint from Lane B gen-7 on #5: I do not touch the client index wiring line; `src/client/brand.ts` edits limited to export additions. Phase: grounding the index/shell-asset seam.

**Comment by chidi21** [comment]
Increment pushed: c2aa64f — Host shell-identity seam. Grounding: the Host serves the SPA through `frontend-static`, which renders every index response (including SPA fallbacks) through `webServer.applyIndexTaps()` and answers `/favicon.svg` + `/manifest.webmanifest` from the upstream dist unless a NAMED route claims them first — named routes are matched before the fallback. So one `ctx.webServer.tapIndex` + two exact routes, registered in the desktop plugin's own `apply()` (which already injects `webServer`), reach compatibility mode, advanced mode, and the same loopback URL opened in a browser.

Landed: `<title>` → Parametria in BOTH modes; brand stylesheet injected in COMPATIBILITY ONLY (the advanced shell already paints those sites from `src/client/brand.ts` — one owner per pixel per mode); favicon + manifest served from the same vendored mark the client paints with (TS literals, so no packaging-closure surface is touched); `windowTitle` and the tray `productName` → Parametria. Brand values are IMPORTED from `src/client/brand.ts`, never restated, and the compat sheet composes its selectors from `UPSTREAM_BRAND_CLASSES` so the existing pin-drift guards stand behind it.

Two findings worth the record: (1) the compat sheet cannot reuse the advanced selectors — those are scoped to `.dshDesktopUpstreamSidebar`/`.dshDesktopConversationSurface` wrappers that do not exist in compat mode, so it is the same treatment re-expressed for the unwrapped DOM, held to the advanced sheet declaration-for-declaration by a new cross-sheet fence; (2) upstream's CSS modules are injected by the shell's module script, i.e. AFTER a document-level sheet, so every superseding rule must outrank rather than tie — a fence asserts that, and it caught a real single-class rule while I wrote it.

DEFERRED (data-migration, not presentation): `main.ts` `PRODUCT_NAME` → `app.setName()` runs before the first `app.getPath('userData')` read, so it names `%APPDATA%\DSH Desktop`; renaming it strands every installed profile/session/log. Same for electron-builder `productName`/`appId` (exe name, NSIS shortcut, AppUserModelID upgrade continuity). Rider done: aria-label drift guard added to `client-brand.spec.ts`'s `it.each`. Next: GUI validation both modes, both themes, then the full gate.

**Comment by chidi21** [comment]
GUI validation DONE (lane-isolated instance, both modes, both themes); full gate running.

Isolation: `DSH_HOME=C:\Users\chidi\.dsh-lane-a` + `--user-data-dir=<lane>\electron-userdata` **with the switch BEFORE the app path** — measured directly (probe app reported `userData=C:\Users\chidi\.dsh-lane-a\electron-userdata` with the switch vs `%APPDATA%\Roaming\Electron` without). Operator's `%APPDATA%\DSH Desktop` mtime unchanged across the whole session (08/19 13:48); Lane B's instance never touched; every process I started was killed.

COMPATIBILITY generation (port 49672, window title **Parametria**): served index has `<title>Parametria</title>`, zero occurrences of 'DeepSeek', brand sheet present before `</head>`; `/favicon.svg` 200 `image/svg+xml` = the Parametria mark with both brand blues; `/manifest.webmanifest` 200 `application/manifest+json` name+short_name Parametria, icon `/favicon.svg`; HEAD 200 with empty body, POST 405. DOM (computed styles): dark — wordmark `"PARAMETRIA"` `rgb(79,195,247)` weight 700 tracking 0.75px, upstream svg `display:none`, rail mark painted from the data URI with its child hidden, hero headline `"Parametric Definitions"` with upstream's 'Into the Unknown' `display:none`; light (via emulated system preference + reload, the genuine boot path) — `rgb(2,136,209)`, same weight/tracking. **The lockup button's accessible name stayed 'New session' in both themes** — the rider's premise confirmed live, not just argued.

ADVANCED generation (port 61012, seeded `settings.yaml` `dsh-desktop.mode: advanced`, window title **Parametria**): served index has the branded title and NO injected `<style>` — the advanced shell keeps painting those sites from its own client sheet, so no mode has two owners. Favicon + manifest branded there too (mode-independent, correctly).

One process note for the record: a browser tab silently drifted onto Lane B's port (50329) mid-run and reported an unbranded shell; caught it by mapping every listening port to its worktree, and every measurement since asserts `location.port` inline before reporting. No conclusion rests on the drifted reading.

**Comment by chidi21** [comment]
PR opened: #29 (head 3dc1d3d). `closingIssuesReferences` verified EMPTY — #29 is not a closing PR by design, and the remainder ships enumerated in its body for RM triage.

Landed: compat-mode brand sheet + `<title>`/favicon/manifest via the Host index seam, `windowTitle` + tray `productName`, and the aria-label rider. Five fence mutations each produced a named failure on a clean tree and were reverted.

TWO THINGS THE RM SHOULD READ BEFORE MERGING:

1. **The gate did not go clean on this box, and I am not calling it benign.** All six non-test steps pass individually (typecheck, closure — 197 nodes closed, cli, loader, profile, licenses). Across four full runs the TEST step failed differently every time, always as a TIMEOUT, never as an assertion, and never in a file this branch touches: fork-worker start timeouts in four `dsh-community-market` specs, then hook/test timeouts in `profile`, `pnpm`, `install-recovery` (×11), `market-pnpm-integration`, `package`. My diff is six files, all under `dsh-plugin-desktop`. The box was concurrently running the other lane's Electron instances and gates. My own specs passed in every run. CI on a clean runner is the authoritative gate — please merge on CI, not on my local tail.

2. **A real defect in my change was caught by `verify:loader`, disclosed in the PR body**: the Loader smoke's minimal `webServer` stub lacked `tapIndex`, so booting the plugin tree threw `ctx.webServer.tapIndex is not a function`. Fixed by completing the stub (the real carrier has had `tapIndex` since the pinned version, and upstream's own ui-theme calls it unconditionally) rather than making the plugin defend against a carrier that cannot occur — second commit.

Deferred with reasons, all needing a decision above my fence: `main.ts` `PRODUCT_NAME`/`app.setName` and the electron-builder `productName`/`appId` (userData relocation + AppUserModelID/installer upgrade continuity — a migration, not a rebrand); app/tray icon artwork (`build/app-icon.png` is sha256-pinned and no rasterized Parametria icon set exists); installer art (no keys set, no files exist); the wider product-name copy in `tray-locale`/recovery window/dialogs/CLI/market locales (needs a naming ruling beyond the mark, e.g. whether 'DSH Terminal' becomes 'Parametria Terminal'); and locale/server-authored copy (upstream's namespace is single-occupant, so it needs a seam that does not exist). Lane A gen-4 ending here.

**Comment by chidi21** [comment]
OWNER RIDER (2026-08-20, in-session, with screenshot — the compat-mode rebrand is confirmed live on the owner's default shell): (1) the expanded sidebar lockup should show the Parametria MARK to the LEFT of the PARAMETRIA wordmark (today the mark appears only at the collapsed rail + hero per PR #28's design); (2) the app icon (titlebar/taskbar) still shows the old mark — that is #31, already in flight. Item (1) is a Lane D slice queued BEHIND #31's merge (both touch src/client/brand.ts — serialize, second lander rebases).

**Comment by chidi21** [comment]
Lane D resolver gen-3 CLAIMED the OWNER RIDER item (1) on #26 — the expanded sidebar lockup gets the Parametria MARK to the LEFT of the PARAMETRIA wordmark. Branch `dg/issue-26-sidebar-mark` (from origin/master a80179a306, i.e. after #34/#31 landed, so the serialize-behind-#31 condition is satisfied). Worktree `C:\Users\chidi\.dsh-resolver-worktrees\issue-26s`, ports 3700+. Scope: strictly client visual — the advanced sheet (`src/client/brand.ts`) AND the compat sheet (`src/client/shell-branding.ts`) now that branding runs in both modes, both themes, with the collapsed-rail icon-only state and the button's accessible name held invariant. Non-closing PR. Phase: grounding the lockup DOM + the two sheets.

**Comment by chidi21** [comment]
Increment pushed: f75079c — the mark is back beside the wordmark in the expanded lockup, in BOTH brand sheets (advanced `src/client/brand.ts`, compat `src/shell-branding.ts`), held identical by the existing cross-sheet declaration fence.

Grounding worth the record: this is a RESTORATION, not an addition. Upstream's `BrandWordmark` (`ui-primitives/src/BrandWordmark.tsx`) is ONE 182x24 svg whose left 24 units are the whale and whose remainder is the letterforms — so PR #28's wordmark-only lockup dropped a graphic that site already had. Geometry measured from that svg rather than chosen: upstream drew 17.04px of mark ink (whale clip 23.16x17.04 in a 24-tall box) with a 3.7px optical gap before the leftmost letterform (x 26.96 vs whale ink ending 23.30). The Parametria mark's ink spans 74.6..425.4 of its 500-unit box = 70.2%, so a **24px box gives 16.8px of ink and 3.6px of its own padding** — both within a fifth of a pixel of upstream's numbers. Hence 24px box, no explicit gap: the gap is already inside the artwork.

Accessible name held: the mark rides `::before` with `content: ""`. Name-from-content gathers generated TEXT, so an empty box contributes nothing **unconditionally** — unlike the wordmark, whose silence depends on upstream's `aria-label` pre-empting name-from-content (the corrected-lockup mechanism). Collapsed rail unaffected: it renders no `.brand` element at all, and every generated box is additionally qualified by upstream's `.hHd-Xa_wide`.

Fences (client-brand 12→13 tests, shell-branding count corrected 3→4 pseudo rules): pinned `::before` declaration; before-precedes-after order; exhaustive 5-rule lockup count with all three generated boxes `.wide`-qualified; mark box asserted textless. Both specs green (26/26), plugin typecheck clean.

One disclosure, NOT touched (Lane D freezes rather than crosses): ADR H-0002's last consequence bullet is now STALE at master — it states "the override reaches advanced mode only… Changing that is a rule change, not a code change", but the BRAND-EVERYWHERE ruling + PR #29 landed compat branding. Raising rather than editing; RM's call whether that one-bullet correction rides a lane or the RM's own doc pass.

Next: GUI validation — both shell modes, both themes, expanded + collapsed sidebar, lane-isolated instance.

**Comment by chidi21** [comment]
OWNER RIDER REFINEMENT (2026-08-20, in-session, with screenshot of the lockup): (1) MORE GAP between the mark and the PARAMETRIA wordmark in the sidebar lockup; (2) the wordmark TEXT color changes from the accent blue to NEUTRAL: dark in light mode, white in dark mode (supersedes the original grounded treatment's accent color FOR THE WORDMARK TEXT ONLY — the mark keeps its own colors; the accent stays wherever else it's used). Folded into Lane D gen-3's active slice.

**Comment by chidi21** [comment]
Owner refinement absorbed — increment pushed: 1b676c6 (both sheets).

**Gap:** the mark gains `margin-right: 8px` on top of the 3.6px its own artwork already supplies. Not eyeballed: 8px is the `gap` upstream itself sets on `.logoRow`, so the space INSIDE the lockup now equals the space between the lockup and the control beside it.

**Neutral ink:** the wordmark now **pins no colour at all** — it inherits. Upstream declares `color: inherit` on `.hHd-Xa_brand` and themes the sidebar's own label ink, so the wordmark is dark on the light sidebar and near-white on the dark one with one declaration and zero theme-conditional rules. This is the arrangement upstream's own wordmark had (its letterforms were `currentColor` inside that same button). Measured live: `rgb(15,17,21)` light / `rgb(249,250,251)` dark, both modes.

**Fact-check, because I nearly shipped the opposite:** I first wrote (in code comments) that the old `body[data-ds-dark-theme]` dark-accent rule was DEAD in compatibility mode, on the reasoning that only the advanced-mode theme presenter sets that attribute. **That is false and I removed it.** Upstream's own theme boot script, inlined into every index response, runs `document.body.toggleAttribute('data-ds-dark-theme', dark)` in BOTH modes — verified in the served document. So PR #29's dark compat measurement was correct and there was no latent defect. The inherit argument stands on its own merits (no palette for us to keep in step with upstream's), not on a defect that does not exist.

**`PARAMETRIA_ACCENT_LIGHT`/`_DARK` are removed.** RM's note said the accent stays wherever else it is used — checked, and the honest answer is nowhere else: the wordmark text was their only consumer in either sheet, so keeping them would be unused exports claiming a use they do not have. Grounded values preserved here for one-commit restoration if a future site wants them: light `#0288d1`, dark `#4fc3f7` (Parametria app `--ptx-accent`).

**GUI validation DONE — 4 launches, all combinations, lane-isolated** (`DSH_HOME=C:\Users\chidi\.dsh-lane-d` + `--user-data-dir` before the app path; operator's `%APPDATA%\DSH Desktop` mtime unchanged at 08/19 13:48 across every launch; every process I started was killed; a second Electron on port 55048 was identified as the OPERATOR'S own instance from the primary checkout and never touched — every measurement asserts `location.port` inline before reporting).

| mode | theme | port | mark box | wordmark | accessible name |
|---|---|---|---|---|---|
| compatibility | light | 55517 | 24x24, mr 8px, painted | `rgb(15,17,21)` 700 0.75px | `New session`, textContent `""` |
| compatibility | dark | 62456 | same | `rgb(249,250,251)` | same |
| advanced | light | 51909 | same | `rgb(15,17,21)` | same |
| advanced | dark | 54978 | same | `rgb(249,250,251)` | same |

Also confirmed live: collapsed rail unchanged (no `.hHd-Xa_brand` element exists there at all, rail mark still painted, no generated box on it); advanced mode's served index carries NO `<style>` and the only live brand sheet is the advanced one — one owner per pixel per mode; hero still reads `Parametric Definitions` with upstream's text `display: none`.

Next: mutation proofs on the committed tree, self `/code-review`, then `corepack yarn check` foreground.

**Comment by chidi21** [comment]
Mutation proofs done, self `/code-review` running, full gate started (foreground). Eight mutations, each applied to a committed tree, each verified applied, each reverted with the tree verified clean before and after — every one produced a NAMED failure: dropped lockup gap; literal colour instead of inherit; the two generated rules swapped in source (only the order assertion can fail there — both declarations still match verbatim); lockup mark rule renamed away; mark unqualified by the expanded-state class; mark box given text; compat gap drifted to 12px; and the new `color:inherit` pin anchor pointed at a fact the bundle lacks. Now running `corepack yarn check`; PR next (non-closing, `closingIssuesReferences` will be verified empty before it opens).

**Comment by chidi21** [comment]
PR opened: **#37** (head `f09a5b74838b1fed315cdd7e16544594461de7eb`). `closingIssuesReferences` verified **[]** — non-closing by design, and the body carries no link keyword adjacent to the reference (I caught and rewrote a "does not close #26" disclaimer in my own draft — that literal token closes regardless of the negation, per the charter's issue-link rule).

Landed: the Parametria mark restored to the LEFT of the PARAMETRIA wordmark in the expanded lockup, in BOTH sheets; `margin-right: 8px` (upstream's own `.logoRow` gap value); wordmark ink neutral by DECLARING NO COLOUR — the sheets now contain zero `color:` declarations and the ink comes from upstream's themed sidebar label ink. `PARAMETRIA_ACCENT_LIGHT/DARK` removed (single consumer each, verified at the merge-base).

**Gate:** `corepack yarn check` exit **0**, foreground, on the committed tree AFTER merging `origin/master` (which had advanced to `da1c7c3` mid-run — the new AGENTS.md L26 text explicitly permits the visual branding this PR ships in compat mode). 67 files / 679 passed / 11 skipped; closure 197 nodes; licenses 524. Clean run, no flakes — no other lanes were running.

**Self `/code-review` found four real defects in my own first pass and all four are fixed, disclosed in the PR body rather than quietly patched.** Three were wrong STATED REASONS (standard 12's class): a geometry claim that swapped axes (17.04 is the whale's clip HEIGHT — the match is height-to-height, and the mark is deliberately ~6.4px narrower because the whale is wide and this mark is square); a gap sentence that contradicted its own numbers (8px declared vs ~11.6px optical); a padding figure that was padding-to-SOLID-ink while the artwork's hairlines run wider. The fourth was mechanical and the most useful: **my ordering fence was vacuous** — `indexOf('::before') < indexOf('::after')` asserts CSS TEXT order, but pseudo-element box order is fixed by the definitions regardless of rule order, so it proved nothing and still went red under a mutation that would not have moved a pixel. Replaced with the mechanism that decides it (mark is the `::before`, wordmark the `::after`) plus a no-reversal guard (`order`/`flex-direction`/`direction`/`row-reverse`); all three real reversal routes now fail a named test.

Also: `color: inherit` was INERT (colour is inherited; a pseudo-element inherits from its originating element), so it is gone and the neutral ink comes from removing the accent pin. **Proven inert by measurement, not argument** — all four mode/theme combinations re-measured after removal and the computed ink is byte-identical to the pre-fix run.

**9 mutation proofs**, each on a committed tree, verified applied, reverted, tree verified clean before and after — every one produced a named failure. **8 GUI launches** (both modes x both themes, twice: before and after the review fixes), lane-isolated, operator's `%APPDATA%\DSH Desktop` mtime unchanged at 08/19 13:48 throughout, every process killed, every measurement asserting `location.port` inline.

**Disclosure, raised not crossed:** ADR H-0002's last consequence bullet is stale at master ("the override reaches advanced mode only… changing that is a rule change") — superseded by the BRAND-EVERYWHERE ruling, PR #29, and now AGENTS.md L26. Both review axes flagged it independently. Lane D freezes rather than crosses scope, so the ledger is untouched; which lane carries the one-bullet correction is the RM's call.

Lane D generation 3 ending here. CI dispatch is the RM's.
